spring.application.name=MyMusic
#spring.application.name=Music-App
# Server Port
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/musicdb

# Elasticsearch Configuration
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=RFVNgPq66DxsY1o_NNw4

# Logging (optional - helps debugging)
logging.level.org.springframework=INFO
